=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/application_settings_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "application_input_streams": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "resolutions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "stream_id": {
                                "type": "string"
                            },
                            "width": {
                                "type": "number"
                            },
                            "height": {
                                "type": "number"
                            },
                            "framerate": {
                                "type": "number"
                            },
                            "pool_max_buffers": {
                                "type": "number"
                            },
                            "scaling_mode": {
                                "type": "string",
                                "enum": [
                                    "STRETCH",
                                    "LETTERBOX_MIDDLE",
                                    "LETTERBOX_UP_LEFT",
                                    "SCALE_AND_CROP"
                                ]
                            }
                        },
                        "additionalProperties": false,
                        "required": [
                            "width",
                            "height",
                            "framerate",
                            "pool_max_buffers"
                        ]
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "method",
                "format",
                "resolutions"
            ]
        },
        "gmv": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "frequency": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "source",
                "frequency"
            ]
        },
        "optical_zoom": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "magnification": {
                    "type": "number"
                },
                "max_dewarping_magnification": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "magnification",
                "enabled"
            ]
        },
        "digital_zoom": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "mode": {
                    "type": "string"
                },
                "magnification": {
                    "type": "number"
                },
                "roi": {
                    "type": "object",
                    "properties": {
                        "x": {
                            "type": "number"
                        },
                        "y": {
                            "type": "number"
                        },
                        "width": {
                            "type": "number"
                        },
                        "height": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "x",
                        "y",
                        "width",
                        "height"
                    ]
                }
            },
            "additionalProperties": false,
            "required": [
                "enabled",
                "mode",
                "magnification",
                "roi"
            ]
        },
        "motion_detection": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "roi": {
                    "type": "object",
                    "properties": {
                        "x": {
                            "type": "number"
                        },
                        "y": {
                            "type": "number"
                        },
                        "width": {
                            "type": "number"
                        },
                        "height": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "x",
                        "y",
                        "width",
                        "height"
                    ]
                },
                "resolution": {
                    "type": "object",
                    "properties": {
                        "width": {
                            "type": "number"
                        },
                        "height": {
                            "type": "number"
                        },
                        "framerate": {
                            "type": "number"
                        },
                        "pool_max_buffers": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "width",
                        "height",
                        "framerate"
                    ]
                },
                "threshold": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "sensitivity_level": {
                    "type": "string"
                },
                "buffer_pool_size": {
                    "type": "number",
                    "minimum": 0,
                    "default": 8
                }
            },
            "additionalProperties": false,
            "required": [
                "enabled",
                "roi",
                "resolution",
                "threshold",
                "sensitivity_level",
                "buffer_pool_size"
            ]
        },
        "rotation": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "angle": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "enabled",
                "angle"
            ]
        },
        "flip": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "direction": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "enabled",
                "direction"
            ]
        },
        "hailort": {
            "type": "object",
            "properties": {
                "device-id": {
                    "type": "string"
                },
                "use-hailort-service": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false,
            "required": [
                "device-id"
            ]
        },
        "application_analytics": {
            "type": "object",
            "properties": {
                "detection": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "analytics_data_id": {
                                "type": "string"
                            },
                            "scaling_mode": {
                                "type": "string",
                                "enum": [
                                    "STRETCH",
                                    "LETTERBOX_MIDDLE",
                                    "LETTERBOX_UP_LEFT"
                                ]
                            },
                            "width": {
                                "type": "integer"
                            },
                            "height": {
                                "type": "integer"
                            },
                            "original_width_ratio": {
                                "type": "integer"
                            },
                            "original_height_ratio": {
                                "type": "integer"
                            },
                            "max_entries": {
                                "type": "integer"
                            },
                            "labels": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "label": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "integer"
                                        }
                                    },
                                    "required": [
                                        "label",
                                        "id"
                                    ]
                                }
                            }
                        },
                        "required": [
                            "analytics_data_id",
                            "labels"
                        ],
                        "dependencies": {
                            "scaling_mode": [
                                "width",
                                "height",
                                "original_width_ratio",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "width": [
                                "scaling_mode",
                                "height",
                                "original_width_ratio",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "height": [
                                "scaling_mode",
                                "width",
                                "original_width_ratio",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "original_width_ratio": [
                                "scaling_mode",
                                "width",
                                "height",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "original_height_ratio": [
                                "scaling_mode",
                                "width",
                                "height",
                                "original_width_ratio",
                                "max_entries"
                            ],
                            "max_entries": [
                                "scaling_mode",
                                "width",
                                "height",
                                "original_width_ratio",
                                "original_height_ratio"
                            ]
                        },
                        "additionalProperties": false
                    }
                },
                "semantic_segmentation": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "analytics_data_id": {
                                "type": "string"
                            },
                            "scaling_mode": {
                                "type": "string",
                                "enum": [
                                    "STRETCH",
                                    "LETTERBOX_MIDDLE",
                                    "LETTERBOX_UP_LEFT"
                                ]
                            },
                            "width": {
                                "type": "integer"
                            },
                            "height": {
                                "type": "integer"
                            },
                            "original_width_ratio": {
                                "type": "integer"
                            },
                            "original_height_ratio": {
                                "type": "integer"
                            },
                            "max_entries": {
                                "type": "integer"
                            },
                            "labels": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "label": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "integer"
                                        }
                                    },
                                    "required": [
                                        "label",
                                        "id"
                                    ]
                                }
                            }
                        },
                        "required": [
                            "analytics_data_id",
                            "labels"
                        ],
                        "dependencies": {
                            "scaling_mode": [
                                "width",
                                "height",
                                "original_width_ratio",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "width": [
                                "scaling_mode",
                                "height",
                                "original_width_ratio",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "height": [
                                "scaling_mode",
                                "width",
                                "original_width_ratio",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "original_width_ratio": [
                                "scaling_mode",
                                "width",
                                "height",
                                "original_height_ratio",
                                "max_entries"
                            ],
                            "original_height_ratio": [
                                "scaling_mode",
                                "width",
                                "height",
                                "original_width_ratio",
                                "max_entries"
                            ],
                            "max_entries": [
                                "scaling_mode",
                                "width",
                                "height",
                                "original_width_ratio",
                                "original_height_ratio"
                            ]
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "version",
        "metadata",
        "application_input_streams",
        "optical_zoom",
        "digital_zoom",
        "rotation",
        "flip",
        "hailort"
    ],
    "additionalProperties": true,
    "$id": "application_settings_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/single_stream_daylight/application_settings.json
{
  "version": "4.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "002668d12f0c62d0825b800ebaeed70556cab0c94894d992cbfbc58e994965b4",
    "description": "",
    "generation_timestamp": "2026-05-31T10:35:22.373121+00:00"
  },
  "application_input_streams": {
    "format": "IMAGE_FORMAT_NV12",
    "method": "INTERPOLATION_TYPE_BILINEAR",
    "resolutions": [
      {
        "framerate": 30,
        "height": 2160,
        "pool_max_buffers": 20,
        "stream_id": "sink0",
        "width": 3840
      }
    ]
  },
  "digital_zoom": {
    "enabled": false,
    "magnification": 1.0,
    "mode": "DIGITAL_ZOOM_MODE_ROI",
    "roi": {
      "height": 1800,
      "width": 2800,
      "x": 200,
      "y": 200
    }
  },
  "flip": {
    "direction": "FLIP_DIRECTION_HORIZONTAL",
    "enabled": false
  },
  "gmv": {
    "frequency": 0.0,
    "source": "isp"
  },
  "hailort": {
    "device-id": "device0"
  },
  "motion_detection": {
    "buffer_pool_size": 20,
    "enabled": true,
    "resolution": {
      "framerate": 30,
      "height": 480,
      "width": 640
    },
    "roi": {
      "height": 480,
      "width": 640,
      "x": 0,
      "y": 0
    },
    "sensitivity_level": "MEDIUM",
    "threshold": 0.5
  },
  "optical_zoom": {
    "enabled": true,
    "magnification": 1.0
  },
  "rotation": {
    "angle": "ROTATION_ANGLE_180",
    "enabled": false
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/frontend_example_jpeg_daylight/application_settings.json
{
  "version": "3.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "587bf04c52e25ab0e9cf66546d044ad3e5dc6c33ed0ceafe76ba5a18b171936b",
    "description": "",
    "generation_timestamp": "2026-03-16T08:17:35.847905+00:00"
  },
  "application_input_streams": {
    "format": "IMAGE_FORMAT_NV12",
    "method": "INTERPOLATION_TYPE_BILINEAR",
    "resolutions": [
      {
        "framerate": 30,
        "height": 1944,
        "pool_max_buffers": 12,
        "width": 2592
      },
      {
        "framerate": 30,
        "height": 720,
        "pool_max_buffers": 12,
        "width": 1280
      }
    ]
  },
  "digital_zoom": {
    "enabled": false,
    "magnification": 1.0,
    "mode": "DIGITAL_ZOOM_MODE_ROI",
    "roi": {
      "height": 1800,
      "width": 2800,
      "x": 200,
      "y": 200
    }
  },
  "flip": {
    "direction": "FLIP_DIRECTION_HORIZONTAL",
    "enabled": false
  },
  "gmv": {
    "frequency": 0.0,
    "source": "isp"
  },
  "hailort": {
    "device-id": "device0"
  },
  "motion_detection": {
    "buffer_pool_size": 8,
    "enabled": false,
    "resolution": {
      "framerate": 30,
      "height": 480,
      "width": 640
    },
    "roi": {
      "height": 480,
      "width": 640,
      "x": 0,
      "y": 0
    },
    "sensitivity_level": "MEDIUM",
    "threshold": 0.5
  },
  "optical_zoom": {
    "enabled": true,
    "magnification": 1.0
  },
  "rotation": {
    "angle": "ROTATION_ANGLE_180",
    "enabled": false
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/application_settings_detection.json
{
  "version": "3.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "bb4f807d1f794fa8a61c8fa78517a988e983929ff2a322e392f0e6e5b7f322bf",
    "description": "",
    "generation_timestamp": "2026-02-24T14:32:59.898268+00:00"
  },
  "application_input_streams": {
    "format": "IMAGE_FORMAT_NV12",
    "method": "INTERPOLATION_TYPE_BILINEAR",
    "resolutions": [
      {
        "framerate": 30,
        "height": 2160,
        "pool_max_buffers": 20,
        "stream_id": "sink0",
        "width": 3840
      },
      {
        "framerate": 30,
        "height": 384,
        "pool_max_buffers": 20,
        "stream_id": "detection_ai",
        "width": 640
      }
    ]
  },
  "digital_zoom": {
    "enabled": false,
    "magnification": 1.0,
    "mode": "DIGITAL_ZOOM_MODE_MAGNIFICATION",
    "roi": {
      "height": 1800,
      "width": 2800,
      "x": 200,
      "y": 200
    }
  },
  "flip": {
    "direction": "FLIP_DIRECTION_NONE",
    "enabled": false
  },
  "gmv": {
    "frequency": 0.0,
    "source": "isp"
  },
  "hailort": {
    "device-id": "device0"
  },
  "motion_detection": {
    "buffer_pool_size": 8,
    "enabled": false,
    "resolution": {
      "framerate": 30,
      "height": 480,
      "width": 640
    },
    "roi": {
      "height": 480,
      "width": 640,
      "x": 0,
      "y": 0
    },
    "sensitivity_level": "MEDIUM",
    "threshold": 0.5
  },
  "optical_zoom": {
    "enabled": false,
    "magnification": 1.0,
    "max_dewarping_magnification": 3.0
  },
  "rotation": {
    "angle": "ROTATION_ANGLE_0",
    "enabled": false
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/face_landmarks_HDR/application_settings.json
{
  "version": "4.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "ed94b99a65f82d9f76f3e06463bdbd4614ba76767878726cfb6786efdc0f1df9",
    "description": "",
    "generation_timestamp": "2026-05-31T10:35:20.501005+00:00"
  },
  "application_input_streams": {
    "format": "IMAGE_FORMAT_NV12",
    "method": "INTERPOLATION_TYPE_BILINEAR",
    "resolutions": [
      {
        "framerate": 30,
        "height": 1944,
        "pool_max_buffers": 12,
        "scaling_mode": "STRETCH",
        "stream_id": "sink0",
        "width": 2592
      },
      {
        "framerate": 30,
        "height": 720,
        "pool_max_buffers": 12,
        "scaling_mode": "STRETCH",
        "stream_id": "sink1",
        "width": 1280
      },
      {
        "framerate": 30,
        "height": 1080,
        "pool_max_buffers": 15,
        "scaling_mode": "STRETCH",
        "stream_id": "sink2",
        "width": 1920
      }
    ]
  },
  "digital_zoom": {
    "enabled": false,
    "magnification": 1.0,
    "mode": "DIGITAL_ZOOM_MODE_MAGNIFICATION",
    "roi": {
      "height": 1300,
      "width": 2300,
      "x": 200,
      "y": 200
    }
  },
  "flip": {
    "direction": "FLIP_DIRECTION_HORIZONTAL",
    "enabled": false
  },
  "gmv": {
    "frequency": 0.0,
    "source": "isp"
  },
  "hailort": {
    "device-id": "device0"
  },
  "motion_detection": {
    "buffer_pool_size": 8,
    "enabled": false,
    "resolution": {
      "framerate": 30,
      "height": 480,
      "width": 640
    },
    "roi": {
      "height": 480,
      "width": 640,
      "x": 0,
      "y": 0
    },
    "sensitivity_level": "MEDIUM",
    "threshold": 0.5
  },
  "optical_zoom": {
    "enabled": true,
    "magnification": 1.0
  },
  "rotation": {
    "angle": "ROTATION_ANGLE_180",
    "enabled": false
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/application_settings.json
{
  "version": "4.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "57c38646a61b4261df3eafc94e94c0ec602f169011da0acf51d8ad9aa2989c79",
    "description": "",
    "generation_timestamp": "2026-06-01T12:09:12.240575+00:00"
  },
  "application_analytics": {
    "semantic_segmentation": [
      {
        "analytics_data_id": "dpm_overflow_detection",
        "height": 1080,
        "labels": [
          {
            "id": 1,
            "label": "person_face"
          },
          {
            "id": 0,
            "label": "vehicle"
          }
        ],
        "max_entries": 3,
        "original_height_ratio": 9,
        "original_width_ratio": 16,
        "scaling_mode": "LETTERBOX_MIDDLE",
        "width": 1920
      }
    ]
  },
  "application_input_streams": {
    "format": "IMAGE_FORMAT_NV12",
    "method": "INTERPOLATION_TYPE_BILINEAR",
    "resolutions": [
      {
        "framerate": 30,
        "height": 2160,
        "pool_max_buffers": 12,
        "stream_id": "sink0",
        "width": 3840
      },
      {
        "framerate": 30,
        "height": 720,
        "pool_max_buffers": 12,
        "stream_id": "dpm_sink1",
        "width": 1280
      },
      {
        "framerate": 30,
        "height": 1080,
        "pool_max_buffers": 30,
        "stream_id": "dpm_sink2",
        "width": 1920
      }
    ]
  },
  "digital_zoom": {
    "enabled": false,
    "magnification": 1.0,
    "mode": "DIGITAL_ZOOM_MODE_ROI",
    "roi": {
      "height": 1800,
      "width": 2800,
      "x": 200,
      "y": 200
    }
  },
  "flip": {
    "direction": "FLIP_DIRECTION_HORIZONTAL",
    "enabled": false
  },
  "gmv": {
    "frequency": 0.0,
    "source": "isp"
  },
  "hailort": {
    "device-id": "device0"
  },
  "motion_detection": {
    "buffer_pool_size": 8,
    "enabled": false,
    "resolution": {
      "framerate": 30,
      "height": 480,
      "width": 640
    },
    "roi": {
      "height": 480,
      "width": 640,
      "x": 0,
      "y": 0
    },
    "sensitivity_level": "MEDIUM",
    "threshold": 0.5
  },
  "optical_zoom": {
    "enabled": true,
    "magnification": 1.0
  },
  "rotation": {
    "angle": "ROTATION_ANGLE_180",
    "enabled": false
  }
}
