=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/profile_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "application_settings": {
            "type": "string"
        },
        "encoded_output_streams": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "encoding": {
                            "type": "string"
                        },
                        "masking": {
                            "type": "string"
                        },
                        "osd": {
                            "type": "string"
                        },
                        "stream_id": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "encoding",
                        "masking",
                        "osd",
                        "stream_id"
                    ]
                }
            ]
        },
        "iq_settings": {
            "type": "string"
        },
        "sensor_config": {
            "type": "string"
        },
        "stabilizer_settings": {
            "type": "string"
        }
    },
    "required": [
        "version",
        "metadata",
        "application_settings",
        "encoded_output_streams",
        "iq_settings",
        "sensor_config",
        "stabilizer_settings"
    ],
    "additionalProperties": true,
    "$id": "profile_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/frontend_api_example_jpeg_HDR_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "99d16f3c8999ee01a2ba40b0b2ce2fce09ac8ca48fad84ed682efcbfd25c16f1",
    "description": "",
    "generation_timestamp": "2026-03-19T09:53:26.630502+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/encoder_sink1.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/masking_sink1.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/frontend_example_jpeg_HDR/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/face_landmarks_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "2371672afb1dd350051b4c05984ff3cd9f9379602c3e3548ad03a1d1640a63e7",
    "description": "",
    "generation_timestamp": "2026-04-15T07:50:14.731361+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/encoder_sink1.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/masking_sink1.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/face_landmarks_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/webserver_lowlight_bayer_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "1ec40b36196e14dc3df465125c98a88f4a17cbba1c1e0919f2a7dcf2511b0ef8",
    "description": "",
    "generation_timestamp": "2026-03-04T12:18:28.201853+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/lowlight/webserver_lowlight_bayer/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/face_landmarks_dual_sensor_sensor_0_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "a4431932cb6518e7d21a392e2c23f19e89a4f6ff51f7a6c536d27e8b351d72db",
    "description": "",
    "generation_timestamp": "2026-03-18T13:31:38.940951+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/encoder_sink0.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/encoder_sink1.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_0_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/webserver_lowlight_detection_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "777df37b0b55f1c4e0766ce5939efd13ae8e68d8a430b87ec589c426bec38e77",
    "description": "",
    "generation_timestamp": "2025-11-25T11:36:55.892704+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/application_settings_detection.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/webserver_lowlight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/webserver_HDR_license_plate_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "95860aae1bdc2d58085c4061ff577ec33f7a1f3858200fe688b0c351b413419a",
    "description": "License plate recognition profile (HDR)",
    "generation_timestamp": "2026-05-06T14:17:09.741065+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/application_settings_detection.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/clip_example_play_from_file_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "489c8205c5426248edc2ecf5d786817323404767b7d60a6e0b28bf085aba476c",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.990746+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/encoder_highres.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/masking_highres.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/osd_highres.json",
      "stream_id": "HighRes"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/encoder_vga.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/masking_vga.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/osd_vga.json",
      "stream_id": "VGA"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/sensor_config_play_from_file.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/webserver_HDR_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "8f8262ac0eff5036cd4f86db44dda2d2c68dda9303f5b1ef0fcc13dd4d384964",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.325399+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/HDR/webserver_HDR/stabilizer_settings.json"
}
