=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/profile_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "application_settings": {
            "type": "string"
        },
        "encoded_output_streams": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "encoding": {
                            "type": "string"
                        },
                        "masking": {
                            "type": "string"
                        },
                        "osd": {
                            "type": "string"
                        },
                        "stream_id": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "encoding",
                        "masking",
                        "osd",
                        "stream_id"
                    ]
                }
            ]
        },
        "iq_settings": {
            "type": "string"
        },
        "sensor_config": {
            "type": "string"
        },
        "stabilizer_settings": {
            "type": "string"
        }
    },
    "required": [
        "version",
        "metadata",
        "application_settings",
        "encoded_output_streams",
        "iq_settings",
        "sensor_config",
        "stabilizer_settings"
    ],
    "additionalProperties": true,
    "$id": "profile_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/ai_example_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "61d1385c74455004733617235813836ab50fcd4833cf029d3968c409ac4b7e46",
    "description": "",
    "generation_timestamp": "2026-03-10T13:53:01.976271+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/encoder_sink1.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/masking_sink1.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/face_landmarks_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "87f4142c308c53754482b8305b84463cfc1d23e7e47aed221eb0ace216fcf5a1",
    "description": "",
    "generation_timestamp": "2026-04-15T07:50:15.642907+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/encoder_sink1.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/masking_sink1.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/face_landmarks_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/frontend_api_example_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "50ac6b4bea560e8d558d18ef4f0983fdacf3bee8701a226fe53e20cc7b391af4",
    "description": "",
    "generation_timestamp": "2026-03-19T09:53:25.816063+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/encoder_sink1.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/masking_sink1.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/frontend_example_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/kit/4k/profiles/daylight/webserver_daylight/webserver_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "51977246f15e6b09a51976799baffcbde384563b9163f675f8b926c449e8fe48",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.282830+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/daylight/webserver_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/daylight/webserver_daylight/encoder_sink0.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/daylight/webserver_daylight/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/daylight/webserver_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/daylight/webserver_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/daylight/webserver_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/webserver_daylight_clip_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "edc28dbd1231f7e90d866ce87c7d8fd6a5372eb2e8b79f8aaa923d65d41090e4",
    "description": "",
    "generation_timestamp": "2026-01-28T16:02:48.200790+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/application_settings_clip.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/encoder_sink0.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/osd_clip.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/clip_example_daylight/encoder_vga.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/osd_clip.json",
      "stream_id": "clip_vga"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/webserver_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/single_stream_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "aacfa0412dbff759c87988b2be80f2a3c955c7b943e91cbe2a13d0778bc70b76",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.540809+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/single_stream_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/frontend_api_example_jpeg_HDR_profile.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "94ad44ac24862d214c6da820e4b813a0ac9ec5ee29a5bcd6f360a3d578fffe69",
    "description": "",
    "generation_timestamp": "2026-02-03T10:28:08.328018+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/encoder_sink1.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/masking_sink1.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/HDR/frontend_example_jpeg_HDR/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_1_daylight/ai_example_dual_sensor_sensor_1_daylight_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "cad521ecc44d54f245551430d1c2b672802d364342b0252f9f2fefcad81411ce",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.598169+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_1_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_1_daylight/encoder_sink0.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_1_daylight/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_1_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_1_daylight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_1_daylight/stabilizer_settings.json"
}
