=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/profile_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "application_settings": {
            "type": "string"
        },
        "encoded_output_streams": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "encoding": {
                            "type": "string"
                        },
                        "masking": {
                            "type": "string"
                        },
                        "osd": {
                            "type": "string"
                        },
                        "stream_id": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "encoding",
                        "masking",
                        "osd",
                        "stream_id"
                    ]
                }
            ]
        },
        "iq_settings": {
            "type": "string"
        },
        "sensor_config": {
            "type": "string"
        },
        "stabilizer_settings": {
            "type": "string"
        }
    },
    "required": [
        "version",
        "metadata",
        "application_settings",
        "encoded_output_streams",
        "iq_settings",
        "sensor_config",
        "stabilizer_settings"
    ],
    "additionalProperties": true,
    "$id": "profile_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/ai_example_lowlight_bayer_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "b076f9762845cc80a85f96759e5b6377c4ace6aa37c57fe464a04ca1d50ffa16",
    "description": "",
    "generation_timestamp": "2025-11-25T11:36:55.790455+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/encoder_sink1.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/masking_sink1.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/lowlight/ai_example_lowlight_bayer/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/webserver_lowlight_bayer_hdr_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "c5f256ba91f023dcfece514047ed6bff29cfb4af54ea80a3bd64c364d9b66098",
    "description": "",
    "generation_timestamp": "2025-11-30T13:04:29.603163+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/lowlight_r0225c8_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "f31bfcd3eefc67104184d77b961df221b74821c142c3a92f0be1f7bcceb29255",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.734275+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/encoder_sink0.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/encoder_sink1.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/clip_example_play_from_file_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "249fa4549aff9046e035be627165ab65943d80e4d2e259a090e871ab86427ccd",
    "description": "",
    "generation_timestamp": "2026-05-10T19:57:51.725881+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/encoder_highres.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/masking_highres.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/osd_highres.json",
      "stream_id": "HighRes"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/encoder_vga.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/masking_vga.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/osd_vga.json",
      "stream_id": "VGA"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/sensor_config_play_from_file.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/clip_example_daylight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/dynamic_privacy_mask_HDR_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "1529b89b7f252ed2d56b98fb6ec20aa00a2f73775358b5fce30c33ead4c1ddaf",
    "description": "",
    "generation_timestamp": "2026-01-15T14:49:09.881205+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/encoder_sink1.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/HDR/dynamic_privacy_mask_HDR/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/webserver_lowlight_detection_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "ad4a4aac2abf18c7fa7d9ceb3106fc5237b09943e59fb522479adb5578797062",
    "description": "",
    "generation_timestamp": "2025-11-25T11:36:56.240793+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/application_settings_detection.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/encoder_sink0.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/webserver_lowlight/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/dynamic_privacy_mask_HDR_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "b9e4d3b4acc5d6991ede99640f3819972105aaac8c4fd654222e41de34c4562b",
    "description": "",
    "generation_timestamp": "2026-01-25T17:32:12.866923+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/application_settings.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/osd_sink0.json",
      "stream_id": "sink0"
    },
    {
      "encoding": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/encoder_sink1.json",
      "masking": "",
      "osd": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/osd_sink1.json",
      "stream_id": "sink1"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/HDR/dynamic_privacy_mask_HDR/stabilizer_settings.json"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/webserver_lowlight_bayer_hdr_license_plate_profile.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "cf9ad2727503390a76f6802f7945a82c5bfeb19fefefb3b5665498098d4a3f1d",
    "description": "License plate recognition profile (denoise HDR)",
    "generation_timestamp": "2026-05-06T14:17:10.653485+00:00"
  },
  "application_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/application_settings_detection.json",
  "encoded_output_streams": [
    {
      "encoding": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/encoder_sink0.json",
      "masking": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/masking_sink0.json",
      "osd": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/osd_sink0.json",
      "stream_id": "sink0"
    }
  ],
  "iq_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/iq_settings.json",
  "sensor_config": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/sensor_config.json",
  "stabilizer_settings": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/lowlight/webserver_lowlight_bayer_hdr/stabilizer_settings.json"
}
