=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/sensor_configuration_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "sensor_configuration": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "drv": {
                    "type": "string"
                },
                "mode": {
                    "type": "integer"
                },
                "pixel_mode": {
                    "type": "integer"
                },
                "sensor_only": {
                    "type": "integer"
                },
                "af_i2c_bus": {
                    "type": "integer"
                },
                "af_i2c_addr": {
                    "type": "string"
                },
                "custom_readout_timing_short": {
                    "type": "integer"
                }
            },
            "required": [
                "name",
                "drv",
                "mode",
                "pixel_mode",
                "sensor_only",
                "af_i2c_bus",
                "af_i2c_addr"
            ],
            "additionalProperties": false
        },
        "sensor_calibration_file": {
            "type": "string"
        },
        "input_video": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string",
                    "enum": [
                        "V4L2SRC",
                        "APPSRC"
                    ],
                    "default": "V4L2SRC"
                },
                "sensor_id": {
                    "type": "string",
                    "enum": [
                        "SENSOR_0",
                        "SENSOR_1"
                    ],
                    "default": "SENSOR_0"
                },
                "resolution": {
                    "type": "object",
                    "properties": {
                        "width": {
                            "type": "number"
                        },
                        "height": {
                            "type": "number"
                        },
                        "framerate": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "width",
                        "height",
                        "framerate"
                    ]
                }
            },
            "additionalProperties": false,
            "required": [
                "resolution"
            ]
        }
    },
    "required": [
        "version",
        "metadata",
        "sensor_configuration",
        "sensor_calibration_file",
        "input_video"
    ],
    "additionalProperties": true,
    "$id": "sensor_configuration_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "a6a47be4bdfc6add54fa1347c191dc68c1e08ab6919d32caff72560507ba7fb4",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.990165+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1944,
      "width": 2592
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/daylight/clip_example_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX675.drv",
    "mode": 0,
    "name": "imx675",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/HDR/dynamic_privacy_mask_HDR/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "c9c42f8c0e2d5cedc844b93f2f91c890b6ae99cc3045c0e848f74b3c1a42d84b",
    "description": "",
    "generation_timestamp": "2026-03-16T10:33:20.658527+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1080,
      "width": 1920
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/HDR/dynamic_privacy_mask_HDR/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX662.drv",
    "mode": 1,
    "name": "imx662",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/ai_example_HDR/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "3b75018c9ccc07ce1591f1b0202d517dcdb43fe52ef5b5c3520f20bd3377e850",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.231283+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/HDR/ai_example_HDR/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 4,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "007bb96baeba511e2179ab8558e9669f74e9b89da0650c583115023cdfa22c1a",
    "description": "",
    "generation_timestamp": "2026-03-10T13:53:01.995023+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1080,
      "width": 1920
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX662.drv",
    "mode": 0,
    "name": "imx662",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/detection_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "336d92520ddcec573d7941a1b75df9153346460d18dda2f4472ad3de130514e0",
    "description": "",
    "generation_timestamp": "2026-02-16T09:40:06.300274+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1080,
      "width": 1920
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/single_stream_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX662.drv",
    "mode": 0,
    "name": "imx662",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/clip_example_daylight/sensor_config_play_from_file.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "0f65d3dda316c750ece9e7208256c356ff4369e38dcb7f83eb3b0e45774a243b",
    "description": "",
    "generation_timestamp": "2026-01-16T01:58:13.413201+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1080,
      "width": 1920
    },
    "sensor_id": "SENSOR_0",
    "source_type": "APPSRC"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx715/theia_sl410m/4k/profiles/daylight/clip_example_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX715.drv",
    "mode": 0,
    "name": "imx715",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/lowlight/frontend_example_jpeg_lowlight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "34c462c5dd381a8e3da7407181eb9d05ce142b588eac84a170f9f0065783ef65",
    "description": "",
    "generation_timestamp": "2026-02-03T08:55:21.468353+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    }
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/lowlight/frontend_example_jpeg_lowlight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX675.drv",
    "mode": 0,
    "name": "imx675",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/daylight/dynamic_privacy_mask_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "b9ba703e619010d7c200a3b780fd64fb2b5d4beada3d0bd01fc8fd80c6c60038",
    "description": "",
    "generation_timestamp": "2026-01-18T17:19:58.821974+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx678/theia_sl410m/4k/profiles/daylight/dynamic_privacy_mask_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 0,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}
