=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/sensor_configuration_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "sensor_configuration": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "drv": {
                    "type": "string"
                },
                "mode": {
                    "type": "integer"
                },
                "pixel_mode": {
                    "type": "integer"
                },
                "sensor_only": {
                    "type": "integer"
                },
                "af_i2c_bus": {
                    "type": "integer"
                },
                "af_i2c_addr": {
                    "type": "string"
                },
                "custom_readout_timing_short": {
                    "type": "integer"
                }
            },
            "required": [
                "name",
                "drv",
                "mode",
                "pixel_mode",
                "sensor_only",
                "af_i2c_bus",
                "af_i2c_addr"
            ],
            "additionalProperties": false
        },
        "sensor_calibration_file": {
            "type": "string"
        },
        "input_video": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string",
                    "enum": [
                        "V4L2SRC",
                        "APPSRC"
                    ],
                    "default": "V4L2SRC"
                },
                "sensor_id": {
                    "type": "string",
                    "enum": [
                        "SENSOR_0",
                        "SENSOR_1"
                    ],
                    "default": "SENSOR_0"
                },
                "resolution": {
                    "type": "object",
                    "properties": {
                        "width": {
                            "type": "number"
                        },
                        "height": {
                            "type": "number"
                        },
                        "framerate": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "width",
                        "height",
                        "framerate"
                    ]
                }
            },
            "additionalProperties": false,
            "required": [
                "resolution"
            ]
        }
    },
    "required": [
        "version",
        "metadata",
        "sensor_configuration",
        "sensor_calibration_file",
        "input_video"
    ],
    "additionalProperties": true,
    "$id": "sensor_configuration_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/kit/5mp/profiles/lowlight/webserver_lowlight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "ee8591870b13f921e3f0861c254ec7e3fae6f843a379dfa6857e007a9ac86485",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.930624+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1944,
      "width": 2592
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/lowlight/webserver_lowlight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX675.drv",
    "mode": 0,
    "name": "imx675",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/IR/face_landmarks_IR/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "0cd6123aca5960565bce5f5974839b4dbec87d06753729a6ce18051f1c099eb8",
    "description": "",
    "generation_timestamp": "2026-04-15T07:50:16.058831+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1944,
      "width": 2592
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/IR/face_landmarks_IR/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX675.drv",
    "mode": 0,
    "name": "imx675",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx307/theia_sl410m/fhd/profiles/daylight/webserver_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "89a5d924918f645fa1faa8a1db3fb00227fb566df336ee7dde44fe64f6e50526",
    "description": "",
    "generation_timestamp": "2026-01-28T17:06:36.364145+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1080,
      "width": 1920
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx307/theia_sl410m/fhd/profiles/daylight/webserver_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX307.drv",
    "mode": 0,
    "name": "imx307",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/kit/4k/profiles/HDR/webserver_HDR/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "b185702e257346b5e3f7fd1bee89161031565e3ef60e645297c78f36b3c1a9c9",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.677154+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/HDR/webserver_HDR/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 4,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx664/theia_sl410m/4mp/profiles/daylight/single_stream_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "c18e764263752d2b8135e240cef14c944239cf59223b9f735673d2cee1742711",
    "description": "",
    "generation_timestamp": "2026-02-02T12:19:10.693986+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1520,
      "width": 2688
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx664/theia_sl410m/4mp/profiles/daylight/single_stream_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX664.drv",
    "mode": 0,
    "name": "imx664",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/IR/ai_example_IR/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "de59b828ee2783e1aa24784e004e8ad37502136af50b487c1ad33608a820ab16",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.749169+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1944,
      "width": 2592
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/IR/ai_example_IR/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX675.drv",
    "mode": 0,
    "name": "imx675",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/kit/5mp/profiles/lowlight/single_stream_lowlight_bayer/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "f9cedcc811bc819d8fd4fd30881dea40ded2a75eafefe9ffea2351db7b5e5e0f",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.952796+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1944,
      "width": 2592
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx675/kit/5mp/profiles/lowlight/single_stream_lowlight_bayer/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX675.drv",
    "mode": 0,
    "name": "imx675",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/gst_example_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "6963c2e50e86f3e2c07931374d853f89e55de3e47dd5d4dded8017ae884e7609",
    "description": "",
    "generation_timestamp": "2026-03-08T10:21:47.830547+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/gst_example_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 0,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}
