=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/sensor_configuration_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "sensor_configuration": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "drv": {
                    "type": "string"
                },
                "mode": {
                    "type": "integer"
                },
                "pixel_mode": {
                    "type": "integer"
                },
                "sensor_only": {
                    "type": "integer"
                },
                "af_i2c_bus": {
                    "type": "integer"
                },
                "af_i2c_addr": {
                    "type": "string"
                },
                "custom_readout_timing_short": {
                    "type": "integer"
                }
            },
            "required": [
                "name",
                "drv",
                "mode",
                "pixel_mode",
                "sensor_only",
                "af_i2c_bus",
                "af_i2c_addr"
            ],
            "additionalProperties": false
        },
        "sensor_calibration_file": {
            "type": "string"
        },
        "input_video": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string",
                    "enum": [
                        "V4L2SRC",
                        "APPSRC"
                    ],
                    "default": "V4L2SRC"
                },
                "sensor_id": {
                    "type": "string",
                    "enum": [
                        "SENSOR_0",
                        "SENSOR_1"
                    ],
                    "default": "SENSOR_0"
                },
                "resolution": {
                    "type": "object",
                    "properties": {
                        "width": {
                            "type": "number"
                        },
                        "height": {
                            "type": "number"
                        },
                        "framerate": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "width",
                        "height",
                        "framerate"
                    ]
                }
            },
            "additionalProperties": false,
            "required": [
                "resolution"
            ]
        }
    },
    "required": [
        "version",
        "metadata",
        "sensor_configuration",
        "sensor_calibration_file",
        "input_video"
    ],
    "additionalProperties": true,
    "$id": "sensor_configuration_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/lowlight/lowlight_bayer_r0225c8/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "60b920b043a82e57b666952949f59b40bce1c77028aab995a23f229e44ffc285",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.326994+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/lowlight/lowlight_bayer_r0225c8/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 0,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx678/kit/4k/profiles/HDR/dynamic_privacy_mask_HDR/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "85b37b22892f05cb1dc4033f50e00b961eb71f83409121879b5f86e7e724f0fd",
    "description": "",
    "generation_timestamp": "2026-01-18T17:52:47.409733+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx678/kit/4k/profiles/HDR/dynamic_privacy_mask_HDR/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "custom_readout_timing_short": 133,
    "drv": "HAILO_IMX678.drv",
    "mode": 4,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/kit/4k/profiles/daylight/ai_example_dual_sensor_sensor_0_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "5d672de68432b9c6edbcf833fb8aa94ecd774c2a334c13761747551be7ee15ac",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.901553+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 15,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/ai_example_dual_sensor_sensor_0_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 0,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/kit/4k/profiles/daylight/dynamic_privacy_mask_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "20300d9e9ca65a84f1259fc5493144091cf1fdc97b36eaf6102a78657377acea",
    "description": "",
    "generation_timestamp": "2026-01-18T17:19:55.942599+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/daylight/dynamic_privacy_mask_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX715.drv",
    "mode": 0,
    "name": "imx715",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/kit/fhd/profiles/daylight/webserver_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "3eb2a0eb614c431257baab28e758ca5ba25ca2ce4e3d1f0fbf5ae9c96230898a",
    "description": "",
    "generation_timestamp": "2026-02-16T09:40:06.362111+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 1080,
      "width": 1920
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15l/imx662/kit/fhd/profiles/daylight/webserver_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX662.drv",
    "mode": 0,
    "name": "imx662",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/webserver_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "1a953150981537c045f372055f96243e88f4ddfad7f4567f8671c6df3635d2ed",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.635810+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/webserver_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 0,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/gst_example_lowlight_bayer/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "bcf24e3bfd34355ae34aa264f03a225edb281ee18a209053c073844f1864b9ea",
    "description": "",
    "generation_timestamp": "2026-03-08T10:21:49.141429+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 30,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx715/kit/4k/profiles/lowlight/gst_example_lowlight_bayer/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX715.drv",
    "mode": 0,
    "name": "imx715",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/kit/4k/profiles/daylight/dual_sensor_single_stream_sensor_0_daylight/sensor_config.json
{
  "version": "1.1.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "8736014a4a01c511d2150c8645e51ff0b339f1502600ec1b650d54242af51bb6",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:21.961478+00:00"
  },
  "input_video": {
    "resolution": {
      "framerate": 15,
      "height": 2160,
      "width": 3840
    },
    "sensor_id": "SENSOR_0"
  },
  "sensor_calibration_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/dual_sensor_single_stream_sensor_0_daylight/calib.json",
  "sensor_configuration": {
    "af_i2c_addr": "0x0",
    "af_i2c_bus": -1,
    "drv": "HAILO_IMX678.drv",
    "mode": 0,
    "name": "imx678",
    "pixel_mode": 0,
    "sensor_only": 0
  }
}
