=== hailo-ai/hailo-camera-configurations/validation/hailo15h/schemas/stabilizer_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "dis": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "minimun_coefficient_filter": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "decrement_coefficient_threshold": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "increment_coefficient_threshold": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "running_average_coefficient": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "std_multiplier": {
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "black_corners_correction_enabled": {
                    "type": "boolean"
                },
                "black_corners_threshold": {
                    "type": "number"
                },
                "average_luminance_threshold": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 255
                },
                "camera_fov_factor": {
                    "type": "number",
                    "minimum": 0.1,
                    "maximum": 1
                },
                "angular_dis": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "vsm": {
                            "type": "object",
                            "properties": {
                                "hoffset": {
                                    "type": "number"
                                },
                                "voffset": {
                                    "type": "number"
                                },
                                "width": {
                                    "type": "number"
                                },
                                "height": {
                                    "type": "number"
                                },
                                "max_displacement": {
                                    "type": "number"
                                }
                            },
                            "required": [
                                "hoffset",
                                "voffset",
                                "width",
                                "height",
                                "max_displacement"
                            ]
                        }
                    },
                    "required": [
                        "enabled",
                        "vsm"
                    ]
                },
                "debug": {
                    "type": "object",
                    "properties": {
                        "generate_resize_grid": {
                            "type": "boolean"
                        },
                        "fix_stabilization": {
                            "type": "boolean"
                        },
                        "fix_stabilization_longitude": {
                            "type": "number"
                        },
                        "fix_stabilization_latitude": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "generate_resize_grid",
                        "fix_stabilization",
                        "fix_stabilization_longitude",
                        "fix_stabilization_latitude"
                    ]
                }
            },
            "additionalProperties": false,
            "required": [
                "enabled",
                "minimun_coefficient_filter",
                "decrement_coefficient_threshold",
                "increment_coefficient_threshold",
                "running_average_coefficient",
                "std_multiplier",
                "black_corners_correction_enabled",
                "black_corners_threshold",
                "average_luminance_threshold",
                "camera_fov_factor",
                "angular_dis",
                "debug"
            ]
        },
        "eis": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "stabilize": {
                    "type": "boolean"
                },
                "eis_config_path": {
                    "type": "string"
                },
                "window_size": {
                    "type": "number"
                },
                "rotational_smoothing_coefficient": {
                    "type": "number"
                },
                "iir_hpf_coefficient": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "camera_fov_factor": {
                    "type": "number",
                    "minimum": 0.1,
                    "maximum": 1
                },
                "line_readout_time": {
                    "type": "number"
                },
                "hdr_exposure_ratio": {
                    "type": "number"
                },
                "min_angle_deg": {
                    "type": "number",
                    "minimum": 0.0,
                    "maximum": 360.0
                },
                "max_angle_deg": {
                    "type": "number",
                    "minimum": 0.0,
                    "maximum": 360.0
                },
                "shakes_type_buff_size": {
                    "type": "number",
                    "minimum": 1
                },
                "force_clamp_correction_angles": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false,
            "required": [
                "enabled",
                "eis_config_path",
                "window_size",
                "rotational_smoothing_coefficient",
                "iir_hpf_coefficient",
                "camera_fov_factor",
                "line_readout_time",
                "hdr_exposure_ratio",
                "min_angle_deg"
            ]
        },
        "gyro": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "sensor_name": {
                    "type": "string"
                },
                "sensor_frequency": {
                    "type": "string"
                },
                "scale": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                }
            },
            "additionalProperties": false,
            "required": [
                "enabled",
                "sensor_name",
                "sensor_frequency",
                "scale"
            ]
        }
    },
    "required": [
        "version",
        "metadata",
        "dis",
        "eis",
        "gyro"
    ],
    "additionalProperties": true,
    "$id": "stabilizer_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/lowlight/webserver_lowlight/stabilizer_settings.json
{
  "version": "1.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "0083c93de0ab73302a36531d6cebc41586232f470e4f166e7865630d7c911cf9",
    "description": "",
    "generation_timestamp": "2025-11-24T12:15:22.698088+00:00"
  },
  "dis": {
    "angular_dis": {
      "enabled": false,
      "vsm": {
        "height": 1080,
        "hoffset": 1856,
        "max_displacement": 64,
        "voffset": 1016,
        "width": 1920
      }
    },
    "average_luminance_threshold": 0,
    "black_corners_correction_enabled": true,
    "black_corners_threshold": 0.5,
    "camera_fov_factor": 0.85,
    "debug": {
      "fix_stabilization": false,
      "fix_stabilization_latitude": 0.0,
      "fix_stabilization_longitude": 0.0,
      "generate_resize_grid": false
    },
    "decrement_coefficient_threshold": 0.001,
    "enabled": false,
    "increment_coefficient_threshold": 0.01,
    "minimun_coefficient_filter": 0.1,
    "running_average_coefficient": 0.033,
    "std_multiplier": 3.0
  },
  "eis": {
    "camera_fov_factor": 0.85,
    "eis_config_path": "/home/root/apps/resources/final_calibration.json",
    "enabled": false,
    "hdr_exposure_ratio": 0.2,
    "iir_hpf_coefficient": 0.997,
    "line_readout_time": 15151,
    "max_angle_deg": 6.0,
    "min_angle_deg": 0.05,
    "rotational_smoothing_coefficient": 0.0,
    "stabilize": true,
    "window_size": 10
  },
  "gyro": {
    "enabled": false,
    "scale": 0.000152716,
    "sensor_frequency": "833.000000",
    "sensor_name": "lsm6dsr_gyro"
  }
}
