=== hailo-ai/hailo-camera-configurations/validation/hailo15l/schemas/medialib_config_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Media Library schema for version configuration",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string",
                    "enum": [
                        "hailo15h",
                        "hailo15l"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "generation_timestamp": {
                    "type": "string"
                }
            },
            "required": [
                "architecture",
                "description",
                "content_hash",
                "generation_timestamp"
            ]
        },
        "default_profile": {
            "type": "string"
        },
        "profiles": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "config_file": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "config_file"
                ]
            }
        },
        "backup_folder_path": {
            "type": "string"
        }
    },
    "required": [
        "version",
        "metadata",
        "default_profile",
        "profiles",
        "backup_folder_path"
    ],
    "additionalProperties": true,
    "$id": "medialib_config_schema"
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx678/kit/4k/medialib_configs/frontend_api_example_jpeg_config.json
{
  "version": "2.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "0d9614bcffea49260cff2b76b94ee84e6d38f24be17b9541b8c0e209d24372c0",
    "description": "",
    "generation_timestamp": "2026-02-03T08:55:21.201502+00:00"
  },
  "backup_folder_path": "/etc/imaging/cfg/backups/frontend_api_example_jpeg",
  "default_profile": "Daylight_JPEG",
  "profiles": [
    {
      "config_file": "/etc/imaging/cfg/hailo15l/imx678/kit/4k/profiles/daylight/frontend_example_jpeg_daylight/frontend_api_example_jpeg_daylight_profile.json",
      "name": "Daylight_JPEG"
    },
    {
      "config_file": "/etc/imaging/cfg/hailo15l/imx675/kit/4k/profiles/HDR/frontend_example_jpeg_HDR/frontend_api_example_jpeg_HDR_profile.json",
      "name": "High_Dynamic_Range_JPEG"
    }
  ]
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx307/theia_sl410m/fhd/medialib_configs/webserver_medialib_config.json
{
  "version": "2.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "a8577f6b7cabecc508d3e7dc3f8fa7a4a9f4a23ebc95cdb6d548b5d09df9df44",
    "description": "",
    "generation_timestamp": "2026-01-28T17:06:36.325512+00:00"
  },
  "backup_folder_path": "/etc/imaging/cfg/backups/webserver",
  "default_profile": "Daylight_Basic",
  "profiles": [
    {
      "config_file": "/etc/imaging/cfg/hailo15l/imx307/theia_sl410m/fhd/profiles/daylight/webserver_daylight/webserver_daylight_profile.json",
      "name": "Daylight_Basic"
    }
  ]
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/kit/4k/medialib_configs/gst_example_medialib_config.json
{
  "version": "2.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "56fefa6501cec1fb89236ffc874e59e10497d2e9f572605a7d5c9168d039dcc8",
    "description": "",
    "generation_timestamp": "2026-03-08T10:21:48.480902+00:00"
  },
  "backup_folder_path": "/etc/imaging/cfg/backups/gst_example",
  "default_profile": "Daylight",
  "profiles": [
    {
      "config_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/gst_example_daylight/gst_example_daylight_profile.json",
      "name": "Daylight"
    },
    {
      "config_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/HDR/gst_example_HDR/gst_example_HDR_profile.json",
      "name": "High_Dynamic_Range"
    },
    {
      "config_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_r0225c8/lowlight_r0225c8_profile.json",
      "name": "Lowlight"
    },
    {
      "config_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/lowlight/lowlight_bayer_r0225c8/lowlight_bayer_r0225c8_profile.json",
      "name": "Lowlight_Bayer"
    },
    {
      "config_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/IR/gst_example_IR/gst_example_IR_profile.json",
      "name": "Infrared"
    }
  ]
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/theia_sl410m/4k/medialib_configs/ai_example_dual_sensor_medialib_config_sensor_0.json
{
  "version": "2.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "0085a3ab8f46e6bde3e0da5a8c374d7afec6c89b803b3bf32995604c5e64576a",
    "description": "",
    "generation_timestamp": "2026-01-04T16:18:48.463338+00:00"
  },
  "backup_folder_path": "/etc/imaging/cfg/backups/ai_example_dual_sensor_sensor_0",
  "default_profile": "Daylight",
  "profiles": [
    {
      "config_file": "/etc/imaging/cfg/hailo15h/imx678/theia_sl410m/4k/profiles/daylight/ai_example_dual_sensor_sensor_0_daylight/ai_example_dual_sensor_sensor_0_daylight_profile.json",
      "name": "Daylight"
    }
  ]
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15h/imx678/kit/4k/medialib_configs/face_landmarks_dual_sensor_medialib_config_sensor_1.json
{
  "version": "2.0.0",
  "metadata": {
    "architecture": "hailo15h",
    "content_hash": "dd8632db1e19e7c825fe1bda9aed19cc7835dbd52a6edebe3af27b9733ff095d",
    "description": "",
    "generation_timestamp": "2026-03-18T13:31:38.877990+00:00"
  },
  "backup_folder_path": "/etc/imaging/cfg/backups/face_landmarks_dual_sensor_sensor_1",
  "default_profile": "Daylight",
  "profiles": [
    {
      "config_file": "/etc/imaging/cfg/hailo15h/imx678/kit/4k/profiles/daylight/face_landmarks_dual_sensor_sensor_1_daylight/face_landmarks_dual_sensor_sensor_1_daylight_profile.json",
      "name": "Daylight"
    }
  ]
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx662/theia_sl410m/fhd/medialib_configs/ai_example_medialib_config.json
{
  "version": "2.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "3984dcdef165953481a96ccdf854a2ee6087fb36effbae5ba3f654524723b83e",
    "description": "",
    "generation_timestamp": "2026-03-10T17:39:10.396311+00:00"
  },
  "backup_folder_path": "/etc/imaging/cfg/backups/ai_example",
  "default_profile": "Daylight",
  "profiles": [
    {
      "config_file": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/daylight/ai_example_daylight/ai_example_daylight_profile.json",
      "name": "Daylight"
    },
    {
      "config_file": "/etc/imaging/cfg/hailo15l/imx662/theia_sl410m/fhd/profiles/HDR/ai_example_HDR/ai_example_HDR_profile.json",
      "name": "High_Dynamic_Range"
    }
  ]
}

=== hailo-ai/hailo-camera-configurations/configurations_tree/cfg/hailo15l/imx675/theia_sl410m/5mp/medialib_configs/clip_example_medialib_config_play_from_file.json
{
  "version": "2.0.0",
  "metadata": {
    "architecture": "hailo15l",
    "content_hash": "3665eb17224de8480c5cc3387fb3312e75d14e1e3e410fe3335dbc6aa1d94dbc",
    "description": "",
    "generation_timestamp": "2026-01-05T13:00:15.625095+00:00"
  },
  "backup_folder_path": "/etc/imaging/cfg/backups/clip_example_play_from_file",
  "default_profile": "PlayFromFile",
  "profiles": [
    {
      "config_file": "/etc/imaging/cfg/hailo15l/imx675/theia_sl410m/5mp/profiles/daylight/clip_example_daylight/clip_example_play_from_file_profile.json",
      "name": "PlayFromFile"
    }
  ]
}
